### ISSUE TITLE
How many Changelist jobs can run at the same time

### ISSUE THREAD

**Issue by nehatomar12** [Isilon/isilon_sdk_8_0_python#33]
Hello

I am using create_job_job API to create changelist job, but when I trigger multiple changelist jobs only 1 get in running state other waits till the job finish 
is there any limitation that we can run only one changelist job at a time?

JOB API:
I have also added allow_dup to True
changelistcreate_params = isi.JobJobChangelistcreateParams(newer_snapid=self.diff_snapid, older_snapid=self.base_snapid)
job_job = isi.JobJobCreateParams(
                              changelistcreate_params=changelistcreate_params,
                              allow_dup=True, type=JobTypes.CHANGELISTCREATE)

<img width="952" alt="Screenshot 2020-08-06 at 12 46 27 PM" src="https://user-images.githubusercontent.com/51879259/89502956-76dd8b00-d7e3-11ea-877a-0dcd8f710e23.png">

**Comment by tenortim** [comment]
Hi @nehatomar12,
The job engine limits are configurable.
Defaults are that up to 3 jobs can be running at once (this is a conservative setting, but we want to avoid taking too many resources away from the actual clients).
There are exclusion sets so that there can only be one job running at one time within a certain set.
Finally, one of the attributes of each job type is whether more than one instance of the job may run at once.

The ChangeList job does not have any exclusion set restrictions. If you wish to allow multiple instances, simply log in to the cluster as root and run the following command:

`# isi_gconfig -t job-config jobs.types.changelistcreate.allow_multiple_instances=true`

That should allow three instances of the job to run in parallel. If you want to e.g. change that limit to 4, then you need to modify the `core.max_jobs` parameter in the same gconfig tree.

**Comment by nehatomar12** [comment]
@tenortim 
After changing allow_multiple jobs to true on cluster it works :)
**isi_gconfig -t job-config jobs.types.changelistcreate.allow_multiple_instances=true**


is there any recommendation for changing limits for max_jobs with respect to configuration?

**Comment by tenortim** [comment]
Hi @nehatomar12,
The default of 3 is considered safe across all configurations including clusters with archive nodes that are less powerful.
You can test changing the value. It is probably pretty safe to change to 4 but any larger value would require careful monitoring to ensure it is not impacting the regular workflow. Certainly if there are Gen 6 A nodes or NL or HD Gen 4/Gen 5 nodes, I would not try to increase past 4.
