### ISSUE TITLE
ProtocolApi.create_nfs_alias() does like object created by 

### ISSUE THREAD

**Issue by jorschra** [Isilon/isilon_sdk_8_0_python#44]
Took me a bit to troubleshoot, when feeding `create_nfs_alias()` an object created using `NfsAliasCreateParams()` with `path`, `name`, and `zone` set, the API rejects it with `Alias "/testnfs_s10" already exists`.

Similar effect when not specifying the zone in the object but specifying the zone on the `create_nfs_alias()` call.

After some testing using `isi` cli tool with the *--debug* flag I found it that it does not like the `health` field included by `NfsAliasCreateParams()` because it is set to `None`. Manually crafting the payload without using `NfsAliasCreateParams()` and omitting the `health` field does work.

I'm guessing `create_nfs_alias()` is not properly dealing with the extra field set to None.

**Comment by suva007** [comment]
Hey hi @jorschra , Thanks for reaching out.

## `Alias "/testnfs_s10" already exists` : Desired behavior
Please follow the below mentioned steps in order to "_create nfs aliases_" using SDK.
- Firstly, please make sure that the `name` you are passing in **`NfsAliasCreateParams()`** function for creating NFS alias, shouldn't be there in alias list .
  You can check that on your oneFS cluster's CLI ,using these commands : 
  

    - `isi nfs aliases list` - It will give you all the aliases present inside System zone.

 

    -  `isi nfs aliases list --zone=Test` - But if you want to see aliases present inside someother zone then , we can view that using this command.

## `isi cli does not like the health field included by NfsAliasCreateParams()` : Desired behavior
- I have opened an internal defect for "_removing the Health parameter_" from POST request body fields , as we don't support this feature of changing the health parameters using CLI or SDK.

- So, after removing this health parameter , as SDK and it's documentations gets automatically generated using swagger-codegen tool , in the future releases as soon as schema changes , the changes will be reflected on the SDK documentation as well.
-  So for now try not to use health parameter and the correct usage for `NfsAliasCreateParams()` can be either seen in `line 21` or `line 22` :  

![image](https://user-images.githubusercontent.com/38084433/140020538-8dbc462d-e905-43d0-b85c-9666e2d3c40a.png)

Let, us know if you face issues with this again.

Thanks & Regards
Suvansh Arora

**Comment by jorschra** [comment]
Hi @suva007

Indeed setting health='unknown' works, complete omitting it is wat was causing the issues.
I'll swap back to NfsAliasCreateParams now instead of manually crafting a payload.
