### ISSUE TITLE
Support to onefs version 9.2.0 and above.

### ISSUE THREAD

**Issue by mukeshguptakc** [Isilon/isilon_sdk_8_0_python#50]
Hello,

we are working on Onefs version 9.2.0. and currently the SDK calls out support to 9.1.0 only.
Are the APIs supported on onefs 9_0_0 be used on onefs version 9.2.0 and above ?

If not then, do we plan to extend isilon_sdk support to onefs version 9.2.0 and above in near future...

**Comment by nalinkanwar** [comment]
Yes, there are definitely plans to extend support to 9.2.0 and above. We're working on restructuring the packaging a bit to make it easier to use. We don't have exact release date yet but we're working on it already. So, some time in near future 🙂

**Comment by mukeshguptakc** [comment]
Hi @nalinkanwar ,
Thank you, for your response.
Just one query we can trigger APIs are backward compatible right.
If we trigger API of isi_sdk_8_0_0 on onefs version 9.2.0 and above it would give the same response.

**Comment by nalinkanwar** [comment]
The way API versioning works in OneFS is each release has an API version associated with it. So, if you're using isi_sdk_8_0_0, you are calling older API version that was released with it. Side effect of this is that you would not be able to use the latest features exposed in the newer API versions. This way of versioning allows customer to upgrade on their own time. (Although, OneFS 8.0.0 is EOSL now so we won't release any newer SDK versions for them; you can still keep using older SDK versions for those; It's just that we don't officially support those versions anymore. Refer https://dl.dell.com/content/docu45445 for details)
And yes, pretty much all APIs are backwards compatible barring a few which had to be deprecated and discontinued due to technical reasons.

**Comment by mukeshguptakc** [comment]
Thank you, @nalinkanwar.
This helps and we would be moving all APIs to isi_sdk_8_2_0.
when we started supporting we used, isi_sdk_8_0_0 and for changelist we used isi_sdk_8_2_0.
So, yes based on features we would refer to specific version and utilise that.

Thank you,
Mukesh Gupta.
