### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'Configuration' and 'str'

### ISSUE THREAD

**Issue by nellaivijay** [Isilon/isilon_sdk_8_0_python#7]
When running simple test script, getting below error message, 
`from __future__ import print_function
import time
import isi_sdk_8_0
from isi_sdk_8_0.rest import ApiException
from pprint import pprint
 
configuration = isi_sdk_8_0.Configuration()
configuration.host = 'https://10.xx.xx.xx:8080'
configuration.username = 'YOUR_USERNAME'
configuration.password = 'YOUR_PASSWORD'
configuration.verify_ssl = False
 
api_instance = isi_sdk_8_0.NamespaceApi(isi_sdk_8_0.ApiClient(configuration))
namespace_path = 'namespace_path_example' # str | Namespace path relative to /.
acl = true # bool | Show access control lists.
nsaccess = true # bool | Indicates that the operation is on the access point instead of the store path. (optional)

try:
    api_response = api_instance.get_acl(namespace_path, acl, nsaccess=nsaccess)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling NamespaceApi->get_acl: %s\n" % e)`

> Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/apis/protocols_api.py", line 5714, in list_nfs_exports
    callback=params.get('callback'))
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/api_client.py", line 347, in call_api
    response_type, auth_settings, callback)
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/api_client.py", line 168, in __call_api
    url = self.host + resource_path
TypeError: unsupported operand type(s) for +: 'Configuration' and 'str'

**Comment by Atomicology** [comment]
@nellaivijay: It appears that you are using an old version of the SDK Python package. Try upgrading your `isi-sdk-8-0` package to v0.2.3. This version is also required for the `NamespaceApi`, since it did not exist in prior versions.

**Comment by dmtucker** [comment]
@Atomicology Is that backwards? IIRC, the `Configuration` object was introduced in 0.2.x. The code here is expecting a `str` but getting that `Configuration` object instead.

@nellaivijay I suspect you may actually need to *prevent* installing 0.2.x.

**Comment by Atomicology** [comment]
@dmtucker: The `Configuration` object was introduced in v0.2.x, which is why the package needs to be updated to properly account for this new object. Before v0.2.x, the host URL was passed instead of the configuration object, which is what the stack trace is showing. I mentioned that v0.2.3 is needed for the example code, because the `NamespaceApi` was introduced in this version. Upgrade is the only path forward here.

**Comment by dmtucker** [comment]
Ah, I missed the `NamespaceApi` usage. That makes sense

**Comment by TharunJohny** [comment]
Hi Vijay,

is the issue resolved by upgrading the version?

I am having a similar code for automation in Cloudera Manger. I use cm_client instead of sdk and i am getting the same error

url = self.host + resource_path
TypeError: unsupported operand type(s) for +: 'Configuration' and 'str'.

Can you tell me how the issue is resolved?
